# Generated by Django 2.2.16 on 2022-03-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220322_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='1', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
