# Generated by Django 2.2.16 on 2022-03-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220322_2137'),
        ('users', '0005_auto_20220323_2007'),
    ]

    operations = [
    ]
